### ISSUE TITLE
redmine 2.6 support and problem with firefox

### ISSUE THREAD

**Issue by hriekehof** [dynamo-media/redmine_issue_detailed_tabs_time#48]
Hi there,

i installed the plugin in redmine 2.6 and it works fine with chrome. People who are using FireFox instead are not seeing any tabs below a ticket.

Would be great if there will be a fix for this

**Comment by brunohanover** [comment]
Hi.

I installed the plugin in redmine 2.6 and DONT works fine.
This is the error code:

```log
Started GET "/issues/9899" for 127.0.0.1 at 2015-01-28 21:58:14 -0300
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"9899"}
  Current user: bruno (id=7)
  Rendered issues/_action_menu.html.erb (3.1ms)
  Rendered plugins/redmine_tags/app/views/issues/_tags.html.erb (1.8ms)
  Rendered plugins/redmine_checklists/app/views/issues/_checklist.html.erb (2.0ms)
  Rendered issue_relations/_form.html.erb (1.4ms)
  Rendered issues/_relations.html.erb (2.6ms)
  Rendered plugins/redmine_issue_detailed_tabs_time/app/views/issues/_history.html.erb (37.6ms)
  Rendered issues/show.html.erb within layouts/base (71.7ms)
Completed 500 Internal Server Error in 269.4ms

ActionView::Template::Error (undefined local variable or method `changesets' for #<#<Class:0x007ffa33f16050>:0x007ffa359d1408>):
    1: <%
    2:   entries = get_issue_history_tab_entries_with changesets
    3:   unless entries.empty?
    4:     tabs = get_issue_history_tabs(entries, journals, changesets).uniq
    5:     selected_tab = get_selected_issue_history_tab(tabs)
  app/views/issues/show.html.erb:120:in `_app_views_issues_show_html_erb___4344243628826372711_70356312585380'
  app/controllers/issues_controller.rb:128:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:125:in `show'
```

**Comment by w0www** [comment]
i install in 2.6 and works fine! more info of errors?

**Comment by hriekehof** [comment]
i close this now to get rid of it in my issue list :)
