### ISSUE TITLE
500 internal error: ActionView::Template::Error (undefined method `get_issue_history_tab_entries'

### ISSUE THREAD

**Issue by cityant** [dynamo-media/redmine_issue_detailed_tabs_time#49]
500 internal error under the following env:
<pre>
Environment:
  Redmine version                2.6.3.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
</pre>

log:
<pre>
ActionView::Template::Error (undefined method `get_issue_history_tab_entries' for #<#<Class:0x007fb565e2b1d0>:0x007fb565e2ec18>):
    2:   stylesheet_link_tag('issue_history_tabs.css', :plugin => :redmine_issue_detailed_tabs_time)
    3: end
    4:
    5: entries = get_issue_history_tab_entries()
    6:
    7: unless entries.empty?
    8:   tabs = get_issue_history_tabs(entries, journals).uniq
  app/views/issues/show.html.erb:120:in `_app_views_issues_show_html_erb__1491719766177637294_70208537828320'
  app/controllers/issues_controller.rb:128:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:125:in `show'

</pre>

**Comment by swiehr** [comment]
I ran into this problem as well, and identified he root cause to be a `require_dependency 'issues_controller'` used in a patch file provided by the other plugin (in my case this was [Redmine Customization Plugin](/Restream/redmine_customize)) - so maybe its a good idea to double check other installed plugins for side effects like that by disabling/reenabling them.
